config/routes.rb
Shoppinglist::Application.routes.draw do
  resources :items
  resources :users, only: [:index, :new, :create]
  resources :auths, only: [:new, :create, :destroy]
  resources :lists

delete "auths" => "auths#destroy"

  root 'items#index'

end

app/models/item.rb
class Item

  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :quantity, type: String
  field :price, type: Float
  field :is_acquired, type: Mongoid::Boolean
  belongs_to :list


validates :name, presence: true
validates :quantity, presence: true
validates :price, presence: true
# ask lorin about validating is_acquried
end

app/models/list.rb
class List
include Mongoid::Document

field :name, :type => String
field :quantity, :type => String
field :price, :type => Integer
belongs_to :user
has_many :items


end

app/models/thelist.rb
class Thelist
  include Mongoid::Document
  include Mongoid::Timestamps
  belongs_to :user
  field :product, :type String
  field :quantity, :type String
  field :price, :type Integer
end

app/models/user.rb
require 'bcrypt'
class User
  include Mongoid::Document
  field :email, type: String
  field :salt, type: String
  field :hashed_password, type: String
  has_many :lists

  attr_accessor :password


  validates :email, uniqueness: true
  
  def authenticate?(password)
  	self.hashed_password == BCrypt::Engine.hash_secret(password, self.salt)
	end

before_save :hash_word

private
	def hash_word
		self.salt =BCrypt::Engine.generate_salt
		self.hashed_password = BCrypt::Engine.hash_secret self.password, self.salt
		self.password = nil
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

    helper_method :current_user

  def current_user
  	if session[:user_id]
  		@current_user ||= User.find(session[:user_id])
  	end
  end

  def authenticate_user
    redirect_to auths_url unless current_user
  end



end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	user = User.find_by(:email => params[:user][:email])
  	if user.authenticate?(params[:user][:password])
  		session[:user_id]=user.id
  		redirect_to lists_path
  	else 
  		redirect_to new_auth_path
  		
  	end
  end

  def destroy
  	session[:user_id]=nil
  	redirect_to new_auth_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end
  

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: 'Item was successfully created!'
    else
      render action: 'new'
    end
  end

  def destroy
    Item.find(params[:id]).destroy
    redirect_to items_path
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    redirect_to items_path, notice: 'Item was successfully updated.'
    else
    render action: 'edit'
    end
  end



  private

  def item_params
    params.require(:item).permit(
      :name, :quantity, :price, :is_acquired
      
    )
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = list.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render action: 'new'
    end    
  end

  def destroy
    list.find(params[:id]).destroy
    redirect_to lists_path
  end

  def show

  end

  def index
    @lists= List.all
  end

  def edit
    @list.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
if @item.update(list_params)
  redirect_to lists_path
else
  render action: 'edit'
end
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end
  def new
  	@user = User.new
end

def create
	@user = User.new(params.require(:user).permit(:email, :password))
	if @user.save
		session[:user_id] = @user.id 
		redirect_to users_path
	else
		render 'new'
	end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auths/new.html.erb
<div class="container">
<h1>Log in!</h1>
<%=form_for @user, {url:auths_path} do |f| %>
<%= f.text_field :email, :placeholder => "Username", class: "form-control" %><br>
<%= f.password_field :password, :placeholder =>"Password", class: "form-control" %><br>
<%= f.submit "Log In!", class: "btn btn-success" %>
<% end %>
</div>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<%= form_for @item do |f| %>
<%= @item.name %>
<div>
<%= f.label :name %>
<%= f.text_field :name, class: "form-control" %>
</div>

<div>
	<%= f.label :quantity %>
	 <%= f.text_field :quantity, class: "form-control" %>
	</div>

<div>
<%= f.label :price %>
 <%= f.text_field :price, class: "form-control" %>
</div>

<div>
<%= f.label :is_acquired?  %> 
<%= f.check_box :is_acquired %>
</div>

<%= f.submit "Update!", class: "btn btn-success" %>
<% end %>

app/views/items/index.html.erb
<h1>My Shopping List</h1>


<table id="item-table">
		
	<thead>
		<tr>
			<th>Name</th> 
			<th>Qty.</th> 
			<th>Price</th> 
			<th>Acquired?</th> 
			
		</tr>
	</thead>

	<% @items.each do |item| %>
		<tr>
			<td><%= item.name %></td>
			<td><%= item.quantity %></td>
			<td><%= item.price %></td>
			<td><%= item.is_acquired %></td>
			<td><%= link_to "Edit", edit_item_path(item), class: "btn btn-primary"  %>  </td>
			<td> <%= link_to 'Delete', item, {method: :delete,confirm: "Are you sure?" } %> </td>
		</tr>

	 
	
	
<% end %>
	
</table>
<%= link_to 'New Item', new_item_path, class: "btn btn-success" %>

<br>
<br>
<br>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= form_for (@item) do |f| %>
		

			<div class="field">
				<%= f.label :name %><br>
				<%= f.text_field :name %>
			</div>
			<div class="field">
				<%= f.label :quantity %><br>
				<%= f.number_field :quantity %>
			</div>

			<div class="field">
				<%= f.label :price %><br>
				<%= f.number_field :price %>

			</div>

			<div class="field">
				<%= f.label "Acquired?" %><br>
				<%= f.check_box :is_acquired %>
			</div>
			<div class="actions">
				<%= f.submit %>
			</div>
			<% end %>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoppinglist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>
<% @lists.each do |l| %> 
	<%= l.name %>
 <% end %>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>

app/views/users/index.html.erb
Welcome, <%= current_user.email %>

<% @users.each do |u| %>

	<%= u.email %> 


<% end %>



<%= link_to "Make New User", new_user_path, class: "btn btn-info" %>

<%= link_to "Log out", auths_path+"/x", {class: "btn btn-info" , method: :delete} %>

app/views/users/new.html.erb
<div class="container">
<h1>Create a New User</h1>
<%=form_for @user do |f| %>
<%= f.text_field :email, :placeholder => "Username", class: "form-control" %><br>
<%= f.password_field :password, :placeholder =>"Password", class: "form-control" %><br>
<%= f.submit "Create New User", class: "btn btn-success" %>
<% end %>
</div>